# Site settings
encoding: UTF-8
title: Saguiitay
disqus_shortname: saguiitay
reading_time:     false
url: "http://www.saguiitay.com" # the base hostname & protocol for your site
future: false

# Owner/author information
owner:
  name:           Itay Sagui
  avatar:         avatar.jpg
  bio:            "My name is Itay Sagui. I'm a software developer, music and literature lover."
  email:          saguiitay@hotmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:     	  saguiitay   
  facebook:       saguiitay
  github:         saguiitay
  stackexchange:  4600/saguiitay
  linkedin:       saguiitay
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    104801352176425964567

  # Background image to be tiled on all pages
background: 


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-687220-5
google_verify:      JGmgphcGsizvSbsgzcbPw2ycvcRov0Dvy-4273CLbFA
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:  876AC79720358512EED988982C214385

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
markdown: kramdown
# highlighter: pygments
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/
  
paginate: 5
paginate_path: "/blog/page:num"

gems: 
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  coderay: true
  
  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: 
  - .htaccess
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

links:
  - url: /windows-phone/
    title: Windows Phone
  - url: /open-source-projects/
    title: Open Source Projects
